name: check-update-go-binary
on: 
  pull_request:
    paths:
      - 'pkg/proto/**'
      - 'pkg/parser/**'

jobs:
  check-go-binary:
    runs-on: ubuntu-latest
    env:
      PARSER_BINARY: pkg/parser/bin/parser
    steps:
    - uses: actions/checkout@v4
    - run: |
        make validate-image-version
      name: Generate go binary

    - name: Compare with master
      run: |
        if ! [ -f "${PARSER_BINARY}" ]; then
          echo "Error: Go binary does not exist. Please run 'make update-contract' to generate the go binary."
          exit 1
        fi
        if cmp -s "${PARSER_BINARY}" "${{ github.event.before }}:${PARSER_BINARY}"; then
          echo "Error: Go binary has not been updated on current branch. Please run 'make update-contract' to update the go binary."
          exit 1
        fi
