name: check-update-go-binary
on: 
  pull_request:
    paths:
      - 'pkg/proto/**'
      - 'pkg/parser/**'

jobs:
  check-go-binary:
    runs-on: ubuntu-latest
    env:
      PARSER_BINARY: pkg/parser/bin/parser
    steps:
    - uses: actions/checkout@v4

    - run: git fetch origin master
      name: Fetch master branch

    - name: Validate Go binary
      run: |
        if ! [ -f "${PARSER_BINARY}" ] && ! [-f "${{ github.workspace }}/${PARSER_BINARY}"]; then
          echo "Error: Go binary has not been generated on current branch. Please run 'make update-contract' to generate the go binary."
          exit 1
        fi
        if cmp -s "${{ github.workspace }}/${PARSER_BINARY}" "${PARSER_BINARY}"; then
          echo "Error: Go binary has not been updated on current branch. Please run 'make update-contract' to update the go binary."
          exit 1
        fi
